spring.application.name=helenacollegepbltest2
#spring.datasource.url = jdbc:mariadb://localhost:3306/demo4
spring.datasource.url=jdbc:postgresql://localhost:5432/helenacollegepbltest2
spring.datasource.username = postgres
spring.datasource.password = password


spring.flyway.url = jdbc:postgresql://localhost:5432/helenacollegepbltest2
spring.flyway.password=password
spring.flyway.user=postgres
spring.flyway.enabled=true

spring.jpa.hibernate.ddl-auto=validate
 
# Show or not log for each sql query
spring.jpa.show-sql = true
 
# Hibernate ddl auto (create, create-drop, update)
#spring.jpa.hibernate.ddl-auto = update
 
# Naming strategy #org.hibernate.cfg.ImprovedNamingStrategy org.hibernate.cfg.ImplicitNamingStrategyJpaCompliantImpl  org.hibernate.cfg.PhysicalNamingStrategyStandardImpl
#spring.jpa.hibernate.naming-strategy = spring.jpa.hibernate.naming.implicit-strategy
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
 
# Use spring.jpa.properties.* for Hibernate native properties (the prefix is
# stripped before adding them to the entity manager)
 
# The SQL dialect makes Hibernate generate better SQL for the chosen database
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
#spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.driver-class-name=org.postgresql.Driver


#spring.main.allow-circular-references=true

#logging.level.root=debug