CREATE SCHEMA hctickets;


CREATE TABLE hctickets.Application (
  Id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  AppName varchar(30) NOT NULL,
  Description varchar(200) NOT NULL,
  CreationDate timestamptz NOT NULL,
  Status varchar(20) NOT NULL
);

CREATE TABLE hctickets.ApplicationRole (
  Id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  RoleName varchar(20) NOT NULL
);

CREATE TABLE hctickets.Role (
  Id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  RoleName varchar(20) NOT NULL
);

CREATE TABLE hctickets.Status (
  Id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Code varchar(20) NOT NULL,
  Value varchar(40) NOT NULL,
  StatusType varchar(20) NOT NULL,
  ItemOrder int4 NOT NULL,
  Active bool NOT NULL
);

CREATE TABLE hctickets.Task (
  Id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Name varchar(60) NOT NULL,
  Details varchar(1000) NOT NULL,
  TicketId int4 NOT NULL,
  UserId int4 NOT NULL,
  Status varchar(20) NOT NULL,
  CreationDate timestamptz NOT NULL,
  CompletedDate timestamptz
);

CREATE TABLE hctickets.Ticket (
  Id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Title varchar(40) NOT NULL,
  Description varchar(600) NOT NULL,
  Status varchar(20) NOT NULL,
  CreatedBy int4 NOT NULL,
  ApplicationId int4 NOT NULL,
  CreationDate timestamptz NOT NULL,
  Visibility varchar(20) NOT NULL,
  ClosedDate timestamptz,
  ClosedBy int4 NOT NULL
);

CREATE TABLE hctickets.TicketAssignment (
  Id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  TicketId int4 NOT NULL,
  TechnicianId int4 NOT NULL,
  ActiveDate timestamptz NOT NULL,
  InactiveDate timestamptz,
  AssignedBy int4 NOT NULL
);

CREATE TABLE hctickets.TicketAttachment (
  Id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  TicketId int4 NOT NULL,
  UserId int4 NOT NULL,
  FileName varchar(75) NOT NULL,
  FilePath varchar(184) NOT NULL,
  FileType varchar(30) NOT NULL,
  FileHash varchar(255) NOT NULL,
  Title varchar(40) NOT NULL,
  GUID uuid NOT NULL,
  DateUpdated timestamptz NOT NULL
);

CREATE TABLE hctickets.TicketComment (
  Id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  TicketId int4 NOT NULL,
  UserId int4,
  CommentText varchar(1000) NOT NULL,
  InternalComment bool NOT NULL,
  CommentDate timestamptz NOT NULL,
  ParentCommentId int4
);

CREATE TABLE hctickets.User (
  Id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  FirstName varchar(40) NOT NULL,
  LastName varchar(40) NOT NULL,
  Email varchar(60) NOT NULL,
  SMSNumber varchar(20),
  CreationDate timestamptz NOT NULL,
  InactiveDate timestamptz,
  Status varchar(20) NOT NULL,
  Salt varchar(255) NOT NULL,
  PasswordHash varchar(255) NOT NULL,
  NotificationPreference varchar(20) NOT NULL,
  RoleId int4 NOT NULL
);

CREATE TABLE hctickets.UserApplicationRole (
  Id int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  AppRoleId int4 NOT NULL,
  UserId int4 NOT NULL,
  AppId int4 NOT NULL,
  Status varchar(20) NOT NULL,
  InactiveDate timestamptz
);

ALTER TABLE hctickets.Task ADD CONSTRAINT fk_Task_Ticket FOREIGN KEY (TicketId) REFERENCES hctickets.Ticket (Id);
ALTER TABLE hctickets.Task ADD CONSTRAINT fk_Task_User FOREIGN KEY (UserId) REFERENCES hctickets.User (Id);

ALTER TABLE hctickets.Ticket ADD CONSTRAINT fk_Ticket_Application FOREIGN KEY (ApplicationId) REFERENCES hctickets.Application (Id);
ALTER TABLE hctickets.Ticket ADD CONSTRAINT fk_Ticket_User FOREIGN KEY (ClosedBy) REFERENCES hctickets.User (Id);

ALTER TABLE hctickets.TicketAssignment ADD CONSTRAINT fk_TicketAssignment_User FOREIGN KEY (TechnicianId) REFERENCES hctickets.User (Id);

ALTER TABLE hctickets.TicketAttachment ADD CONSTRAINT fk_TicketAttachment_Ticket FOREIGN KEY (TicketId) REFERENCES hctickets.Ticket (Id);
ALTER TABLE hctickets.TicketAttachment ADD CONSTRAINT fk_TicketAttachment_User FOREIGN KEY (UserId) REFERENCES hctickets.User (Id);

ALTER TABLE hctickets.TicketComment ADD CONSTRAINT fk_TicketComment_Ticket FOREIGN KEY (TicketId) REFERENCES hctickets.Ticket (Id);
ALTER TABLE hctickets.TicketComment ADD CONSTRAINT fk_TicketComment_User FOREIGN KEY (UserId) REFERENCES hctickets.User (Id);
ALTER TABLE hctickets.TicketComment ADD CONSTRAINT fk_TicketComment_TicketComment FOREIGN KEY (ParentCommentId) REFERENCES hctickets.TicketComment (Id);

ALTER TABLE hctickets.User ADD CONSTRAINT fk_User_Role FOREIGN KEY (RoleId) REFERENCES hctickets.Role (Id);

ALTER TABLE hctickets.UserApplicationRole ADD CONSTRAINT fk_UserApplicationRole_User FOREIGN KEY (UserId) REFERENCES hctickets.User (Id);
ALTER TABLE hctickets.UserApplicationRole ADD CONSTRAINT fk_UserApplicationRole_ApplicationRole FOREIGN KEY (AppRoleId) REFERENCES hctickets.ApplicationRole (Id);
ALTER TABLE hctickets.UserApplicationRole ADD CONSTRAINT fk_UserApplicationRole_Application FOREIGN KEY (AppId) REFERENCES hctickets.Application (Id);
